from datetime import timedelta
from feast import Entity, FeatureView, Field, FileSource
from feast.types import Float64, String

# ── 1. Define Entity ──────────────────────────────────────────────────────────
# The entity is the primary key used to retrieve features.
customer = Entity(
    name="customer",
    join_keys=["customer_id"],
    description="Bank customer",
)

# ── 2. Define Data Source ─────────────────────────────────────────────────────
# Point to the Parquet file generated by our feature SQL pipeline.
customer_features_source = FileSource(
    name="customer_features_source",
    path="data/customer_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_at",
)

# ── 3. Define Feature View ────────────────────────────────────────────────────
# A Feature View groups features that are computed and materialized together.
customer_features_view = FeatureView(
    name="customer_features_view",
    entities=[customer],
    ttl=timedelta(days=2),  # How far back to look for latest features
    source=customer_features_source,
    schema=[
        # Model features
        Field(name="credit_score", dtype=Float64),
        Field(name="emi_to_income_ratio", dtype=Float64),
        Field(name="salary_delay_days", dtype=Float64),
        Field(name="savings_decline_pct", dtype=Float64),
        Field(name="income_drop_pct", dtype=Float64),
        Field(name="credit_utilization_ratio", dtype=Float64),
        Field(name="failed_autodebit_count", dtype=Float64),
        Field(name="missed_payments_last_6m", dtype=Float64),
        Field(name="utility_payment_delay_days", dtype=Float64),
        Field(name="discretionary_spend_drop_pct", dtype=Float64),
        Field(name="gambling_spend_increase_pct", dtype=Float64),
        Field(name="balance_volatility_30d", dtype=Float64),
        Field(name="atm_withdrawal_increase_pct", dtype=Float64),
        Field(name="atm_withdrawal_count_30d", dtype=Float64),
        Field(name="upi_lending_app_txn_count", dtype=Float64),
        Field(name="recent_failed_autodebit_flag", dtype=Float64),
        Field(name="savings_decline_trend", dtype=Float64),
        Field(name="risk_momentum_score", dtype=Float64),
        Field(name="emi_credit_stress", dtype=Float64),
        Field(name="liquidity_stress", dtype=Float64),
        Field(name="payment_failure_severity", dtype=Float64),
        Field(name="behavioral_risk_score", dtype=Float64),
        Field(name="volatility_liquidity_risk", dtype=Float64),
        Field(name="composite_stress_index", dtype=Float64),
        Field(name="month", dtype=Float64),
        Field(name="quarter", dtype=Float64),
        Field(name="month_sin", dtype=Float64),
        Field(name="month_cos", dtype=Float64),
        Field(name="customer_segment_salaried", dtype=Float64),
        Field(name="customer_segment_self_employed", dtype=Float64),
        Field(name="geography_rural", dtype=Float64),
        Field(name="geography_tier2", dtype=Float64),
        Field(name="risk_cohort_moderate", dtype=Float64),
        Field(name="risk_cohort_stable", dtype=Float64),
    ],
)
